services:
  debezium:
    image: debezium/connect:1.4
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "debezium"
      CONFIG_STORAGE_TOPIC: "debezium-connect-configs"
      OFFSET_STORAGE_TOPIC: "debezium-connect-offsets"
      STATUS_STORAGE_TOPIC: "debezium-connect-status"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      PLUGIN_PATH: "/kafka/connect"
    depends_on:
      - postgres
      - kafka
    ports:
      - 8083:8083
    volumes:
      - ./debezium-config:/kafka/connectors
    command: ["bash", "-c", "sleep 10 && curl -X POST -H 'Content-Type: application/json' --data @/kafka/connectors/config.json http://localhost:8083/connectors"]
