services:
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=True
      - SERVER_DEFINITION_FILE=/pgadmin4/servers.json
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - postgres